baseURL = "https://hankail05.github.io"
languageCode = "kr-ko"
title = "가지 않은 길"
theme = "Mainroad"
paginate = 10
disqusShortname = "hankail05-github-io"
googleAnalytics = "UA-164655053-1"
canonifyURLs = true

[Params]
subtitle = "진귀한 글을 적기 위해 노력함"
description = "진귀한 글을 적기 위해 노력함"
images = ["images/main.png"]
copyright = "hankail05"
comments = true
opengraph = true
twitter_cards = false
readmore = true
authorbox = false
toc = false
post_navagation = true
post_meta = ["date"]
mainSections = ["post"]
dateformat = "2006-01-02"
mathjax = true
mathjaxPath = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.0.1/es5/sre/sre_browser.min.js"
mathjaxConfig = "TeX-AMS-MML_HTMLorMML"
highlightColor = "#7690f3"

[Params.sidebar]
home = "right"
list = "right"
single = "right"
widgets = ["recent", "categories", "social", "taglist"]

[Params.widgets]
recent_num = 5
tags_counter = true

[Params.widgets.social]
#facebook = "username"
#twitter = "username"
#instagram = "username"
#linkedin = "username"
#telegram = "username"
#github = "hankail05"
#gitlab = "username"
#bitbucket = "username"
#email = "hankail0582@gmail.com"

[outputs]
home = ["HTML", "RSS"]
enableRobotsTXT = true

[sitemap]
changefreq = "weekly"
filename = "sitemap.xml"
